MONGODB_HOST: mongodb-{{ env }}.kranthi.fun # mongodb-dev.kranthi.fun
REDIS_HOST: redis-{{ env }}.kranthi.fun
CATALOGUE_HOST: catalogue-{{ env }}.kranthi.fun
CART_HOST: cart-{{ env }}.kranthi.fun
USER_HOST: user-{{ env }}.kranthi.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.kranthi.fun
MYSQL_HOST: mysql-{{ env }}.kranthi.fun
SHIPPING_HOST: shipping-{{ env }}.kranthi.fun
PAYMENT_HOST: payment-{{ env }}.kranthi.fun